name: Build firmware

on: push

jobs:
    build-firmware:
        runs-on: ubuntu-22.04
        container:
            image: ghcr.io/retrofun/mist-firmware-builder
        steps:
          - name: Checkout
            id: checkout
            uses: actions/checkout@v4

          - name: Build
            id: build
            run: BASE=/opt/arm-none-eabi/bin/arm-none-eabi make

          - name: Get current date
            id: date
            run: echo "date=$(date '+%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

          - name: Save artifacts
            id: artifacts
            uses: actions/upload-artifact@v4
            with:
              name: mist-firmware-binaries-${{ steps.date.outputs.date }}
              path: |
                firmware.bin
                firmware.hex
                firmware.upg
